# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: curl "https://dev87841.service-now.com/api/now/table/change_request" \
                --request POST \
                --header "Accept:application/json" \
                --header "Content-Type:application/json" \
                --data "{\"start_date\":\"$(Date:yyyy-MM-dd HH:mm:ss)",\"description\":\"\\\"Demo DotNet application Release request for https://dev.azure.com/utilitieslabDemo01/demoDotnet/_build/results?buildId=$(Build.BuildId)&view=results , Github Commit  id $(Build.SourceVersion) and Commit Message $(Build.SourceVersionMessage)\\\"\",\"priority\":\"3\"}" \
                --user 'admin':'Quetro@#$7028'
