name:  $(Date:yyyyMMdd)$(Rev:.r)


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      startDATE=$(date '+%Y-%m-%d %H:%M:%S') && endDATE=$(date '+%Y-%m-%d %H:%M:%S -d "+1 day") && curl "https://dev87841.service-now.com/api/now/table/change_request" \
            --request POST \
            --header "Accept:application/json" \
            --header "Content-Type:application/json" \
            --data "{\"start_date\":\"$DATE\",\"end_date\":\"$DATE +1\",\"description\":\"Demo DotNet application Release request for https://dev.azure.com/utilitieslabDemo01/demoDotnet/_build/results?buildId=$(Build.BuildId)&view=results , Github Commit  id $(Build.SourceVersion) and Commit Message $(Build.SourceVersionMessage)\"}" \
            --user 'admin':'Quetro@#$7028'
